version: "3"
services:
  sls:
    build: .
    container_name: sls_template
    tty: true
    volumes:
      - .:/opt/app
      - bundle:/root/.anyenv/envs/rbenv
    ports:
      - "3000:3000"
    environment:
      - DEFAULT_REGION=ap-northeast-1
      - LOCALSTACK_HOST=localstack
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_template
    ports:
      - "4566:4566"
    environment:
      - DEBUG=true
      - DEFAULT_REGION=ap-northeast-1
      - HOSTNAME=localstack
      - LOCALSTACK_HOSTNAME=localstack
      - DATA_DIR=${DATA_DIR- }
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
  dynamodb_admin:
    image: aaronshaf/dynamodb-admin
    tty: true
    container_name: dynamodb_admin
    ports:
      - "8001:8001"
    depends_on:
      - localstack
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
      - AWS_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}

volumes:
  bundle: